// <auto-generated />
using System;
using SET.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SET.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211216001519_AddRelationshipsOfChallengeModel")]
    partial class AddRelationshipsOfChallengeModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookReading", b =>
                {
                    b.Property<Guid>("ReadBooksDuringChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReadingFinishedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReadBooksDuringChallengeId", "ReadingFinishedId");

                    b.HasIndex("ReadingFinishedId");

                    b.ToTable("BookReading");
                });

            modelBuilder.Entity("DietRecipe", b =>
                {
                    b.Property<Guid>("FitDietsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FitDietsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("DietRecipe");
                });

            modelBuilder.Entity("NoticeReminder", b =>
                {
                    b.Property<Guid>("NoticesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RemindersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NoticesId", "RemindersId");

                    b.HasIndex("RemindersId");

                    b.ToTable("NoticeReminder");
                });

            modelBuilder.Entity("PersonalPrincipleUser", b =>
                {
                    b.Property<Guid>("PersonalPrinciplesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonalPrinciplesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("PersonalPrincipleUser");
                });

            modelBuilder.Entity("Shared.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TimesRead")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReadingId")
                        .IsUnique()
                        .HasFilter("[ReadingId] IS NOT NULL");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Shared.Models.BuiltInFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BuiltInFrequencies");
                });

            modelBuilder.Entity("Shared.Models.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChallangeName")
                        .HasColumnType("int");

                    b.Property<string>("Foundator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlWithFullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserStatusInChallenge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("Shared.Models.DevelopmentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DevelopmentPlanType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DevelopmentPlans");
                });

            modelBuilder.Entity("Shared.Models.Diet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diets");
                });

            modelBuilder.Entity("Shared.Models.EndRepeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Never")
                        .HasColumnType("bit");

                    b.Property<int?>("Timer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EndRepeats");
                });

            modelBuilder.Entity("Shared.Models.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilePurpose")
                        .HasColumnType("int");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FileEntities");
                });

            modelBuilder.Entity("Shared.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityArea")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonToAchieve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Shared.Models.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcquiredUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityArea")
                        .HasColumnType("int");

                    b.Property<int>("DaysCountToAchieve")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NegativeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OvercomeNegativeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PositiveUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimesCountExecutedAct")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfHabit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcquiredUserId");

                    b.HasIndex("NegativeUserId")
                        .IsUnique()
                        .HasFilter("[NegativeUserId] IS NOT NULL");

                    b.HasIndex("OvercomeNegativeUserId");

                    b.HasIndex("PositiveUserId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("Shared.Models.Notice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("From")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RepeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("HabitId")
                        .IsUnique();

                    b.HasIndex("RepeatId");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("Shared.Models.NoticeRepeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuiltInFrequencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EndRepeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserFrequencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuiltInFrequencyId");

                    b.HasIndex("EndRepeatId");

                    b.HasIndex("UserFrequencyId");

                    b.ToTable("NoticeRepeats");
                });

            modelBuilder.Entity("Shared.Models.PersonalPrinciple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonToFollow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonalPrinciples");
                });

            modelBuilder.Entity("Shared.Models.Rd71", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletedDays")
                        .HasColumnType("int");

                    b.Property<Guid?>("DietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEasyVersion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MinTimeWorkoutExecute")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId")
                        .IsUnique();

                    b.HasIndex("DietId");

                    b.HasIndex("ReadingId")
                        .IsUnique();

                    b.HasIndex("UserTaskId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Rd71s");
                });

            modelBuilder.Entity("Shared.Models.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("Shared.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Shared.Models.RecomendedBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecomendedBooks");
                });

            modelBuilder.Entity("Shared.Models.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("TimeToMainNotice")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Shared.Models.Statement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("285c679e-ac53-44bb-b730-5c02525da1d9"),
                            Author = "Albert Einstein",
                            Text = "We cannot solve problems with the kind of thinking we employed when we came up with them."
                        },
                        new
                        {
                            Id = new Guid("e5e0d97e-387c-4c70-bf98-4ac5ba9e0c75"),
                            Author = "Mahatma Gandhi",
                            Text = "Learn as if you will live forever, live like you will die tomorrow."
                        },
                        new
                        {
                            Id = new Guid("583141ba-5693-4882-b0c9-836b292ad0a5"),
                            Author = "Mark Twain",
                            Text = "Stay away from those people who try to disparage your ambitions. Small minds will always do that, but great minds will give you a feeling that you can become great too."
                        },
                        new
                        {
                            Id = new Guid("49bfc941-d4fb-4e47-8970-36e1acb7666f"),
                            Author = "Eleanor Roosevelt",
                            Text = "When you give joy to other people, you get more joy in return. You should give a good thought to happiness that you can give out."
                        },
                        new
                        {
                            Id = new Guid("215d0c54-8626-4dee-8a57-9a014ee4f86b"),
                            Author = "Norman Vincent Peale",
                            Text = "When you change your thoughts, remember to also change your world."
                        },
                        new
                        {
                            Id = new Guid("1f683e33-2d88-4911-a182-11e4dd596ce2"),
                            Author = "Walter Anderson",
                            Text = "It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest."
                        },
                        new
                        {
                            Id = new Guid("3bf2ebc6-dc80-4a05-856d-9ae4007f5ab5"),
                            Author = "Diane McLaren",
                            Text = "Nature has given us all the pieces required to achieve exceptional wellness and health, but has left it to us to put these pieces together."
                        },
                        new
                        {
                            Id = new Guid("b97d4505-be37-468e-8ea7-5a03c50b7086"),
                            Author = "Alexander Graham Bell",
                            Text = "Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus."
                        },
                        new
                        {
                            Id = new Guid("6738d4af-195c-450c-943a-2df7b1d0b185"),
                            Author = "Jim Rohn",
                            Text = "Either you run the day or the day runs you."
                        },
                        new
                        {
                            Id = new Guid("da681396-df8a-442b-bd34-0e4297e6302a"),
                            Author = "Thomas Jefferson",
                            Text = "I’m a greater believer in luck, and I find the harder I work the more I have of it."
                        },
                        new
                        {
                            Id = new Guid("88f9ad2b-886a-4533-a57b-394312f82338"),
                            Author = "Paulo Coelho",
                            Text = "When we strive to become better than we are, everything around us becomes better too."
                        },
                        new
                        {
                            Id = new Guid("a690ffdb-fe3b-461e-835f-93cafdf3e793"),
                            Author = "Thomas Edison",
                            Text = "Opportunity is missed by most people because it is dressed in overalls and looks like work."
                        },
                        new
                        {
                            Id = new Guid("e31e0caf-8024-4615-bb6b-2c4743530599"),
                            Author = "Tony Robbins",
                            Text = "Setting goals is the first step in turning the invisible into the visible."
                        },
                        new
                        {
                            Id = new Guid("c1acb468-a185-47f3-b29a-682c2bcd77d6"),
                            Author = "Steve Jobs",
                            Text = "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it."
                        },
                        new
                        {
                            Id = new Guid("240c8126-04c5-431d-8dbb-a1fc5aedcdd4"),
                            Author = "Alexandra of The Productivity Zone",
                            Text = "It’s not about better time management. It’s about better life management"
                        },
                        new
                        {
                            Id = new Guid("b9884e4a-2b0c-4153-9de3-473fc234cdfb"),
                            Author = "Winston Churchill",
                            Text = "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty."
                        },
                        new
                        {
                            Id = new Guid("206fa100-2b20-4075-8b5a-d7c8e6a27d0f"),
                            Author = "Will Rogers",
                            Text = "Don’t let yesterday take up too much of today."
                        },
                        new
                        {
                            Id = new Guid("33f62015-1aea-44c8-9f8a-9d10c968a5cb"),
                            Text = "You learn more from failure than from success. Don’t let it stop you. Failure builds character."
                        },
                        new
                        {
                            Id = new Guid("6203dbdb-21ba-493a-89a7-d2dd29f0f4f6"),
                            Author = "Steve Jobs",
                            Text = "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you."
                        },
                        new
                        {
                            Id = new Guid("2bba8f29-0959-437d-9f27-796f7cd0df38"),
                            Author = "Vernon Sanders Law",
                            Text = "Experience is a hard teacher because she gives the test first, the lesson afterwards."
                        },
                        new
                        {
                            Id = new Guid("dec249b9-530f-4f00-940e-6eb749be6adb"),
                            Author = "Dorothy West",
                            Text = "To know how much there is to know is the beginning of learning to live."
                        },
                        new
                        {
                            Id = new Guid("bbfb9134-839e-4b84-8ebd-767d97d5732d"),
                            Author = "Tony Robbins",
                            Text = "Goal setting is the secret to a compelling future."
                        },
                        new
                        {
                            Id = new Guid("b6abc218-e9bd-4ed7-8420-b91e0fc8746e"),
                            Author = "Dalai Lama",
                            Text = "Just one small positive thought in the morning can change your whole day."
                        },
                        new
                        {
                            Id = new Guid("b69f7608-642c-4eb4-9b86-e8b25f9631af"),
                            Author = "Chris Grosser",
                            Text = "Opportunities don't happen, you create them."
                        },
                        new
                        {
                            Id = new Guid("2ec6074a-b14b-4944-b28f-37d140264fdd"),
                            Author = "Gary Vaynerchuk",
                            Text = "Love your family, work super hard, live your passion."
                        },
                        new
                        {
                            Id = new Guid("2f1659a7-e76e-4cbb-843e-39bd413ab7b2"),
                            Author = "George Eliot",
                            Text = "It is never too late to be what you might have been."
                        },
                        new
                        {
                            Id = new Guid("ade0c6c9-2bb4-48fa-a493-66a33cc23cbc"),
                            Author = "Les Brown",
                            Text = "Don't let someone else's opinion of you become your reality"
                        },
                        new
                        {
                            Id = new Guid("39ca9573-bf27-41ce-8d48-e34b1ad6d4ab"),
                            Author = "Mark Cuban",
                            Text = "If you’re not positive energy, you’re negative energy."
                        },
                        new
                        {
                            Id = new Guid("33aaa188-cf3f-436b-80a7-bde031a116ee"),
                            Author = "Stephen R. Covey",
                            Text = "I am not a product of my circumstances. I am a product of my decisions."
                        },
                        new
                        {
                            Id = new Guid("e031f458-543d-49af-b0f5-66d269d5f5e1"),
                            Author = "Arlan Hamilton",
                            Text = "I can’t tell you how many times I’ve been given a no. Only to find that a better, brighter, bigger yes was right around the corner."
                        },
                        new
                        {
                            Id = new Guid("bb0eec82-c6b9-4fb9-810d-9f6aa722fef0"),
                            Author = "Mark Twain",
                            Text = "The two most important days in your life are the day you’re born and the day you find out why."
                        },
                        new
                        {
                            Id = new Guid("47e3aee6-26ed-4049-b9af-98abfe9d395c"),
                            Author = "Pema Chodron",
                            Text = "Nothing ever goes away until it teaches us what we need to know."
                        },
                        new
                        {
                            Id = new Guid("ce85dbbd-fb4c-4fbe-892b-26604be094fa"),
                            Author = "Bruce Lee",
                            Text = "We can see through others only when we can see through ourselves."
                        },
                        new
                        {
                            Id = new Guid("7eeba12f-4404-4954-90a5-6a4572095f43"),
                            Author = "Robert Frost",
                            Text = "The best way out is always through."
                        },
                        new
                        {
                            Id = new Guid("64a61ce9-9c28-4f17-a883-c160e4eeba92"),
                            Author = "Frederick Douglass",
                            Text = "If there is no struggle, there is no progress."
                        },
                        new
                        {
                            Id = new Guid("e708ae68-04a0-415b-8070-f4f8bea3dcd9"),
                            Author = "Ruth Gordo",
                            Text = "Courage is like a muscle. We strengthen it by use"
                        },
                        new
                        {
                            Id = new Guid("06c74ab3-da07-4fd1-9865-45b81a1cf811"),
                            Author = "Cormac McCarthy",
                            Text = "Keep a little fire burning; however small, however hidden."
                        });
                });

            modelBuilder.Entity("Shared.Models.TimeZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NoticeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NoticeId")
                        .IsUnique()
                        .HasFilter("[NoticeId] IS NOT NULL");

                    b.ToTable("TimeZones");
                });

            modelBuilder.Entity("Shared.Models.TrainingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeExecuteForOneTraining")
                        .HasColumnType("time");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DevelopmentPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentPlanId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shared.Models.UserFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Frequency")
                        .HasColumnType("time");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserFrequencies");
                });

            modelBuilder.Entity("Shared.Models.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityArea")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("Shared.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("BookReading", b =>
                {
                    b.HasOne("Shared.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("ReadBooksDuringChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Reading", null)
                        .WithMany()
                        .HasForeignKey("ReadingFinishedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DietRecipe", b =>
                {
                    b.HasOne("Shared.Models.Diet", null)
                        .WithMany()
                        .HasForeignKey("FitDietsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoticeReminder", b =>
                {
                    b.HasOne("Shared.Models.Notice", null)
                        .WithMany()
                        .HasForeignKey("NoticesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Reminder", null)
                        .WithMany()
                        .HasForeignKey("RemindersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalPrincipleUser", b =>
                {
                    b.HasOne("Shared.Models.PersonalPrinciple", null)
                        .WithMany()
                        .HasForeignKey("PersonalPrinciplesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Book", b =>
                {
                    b.HasOne("Shared.Models.Reading", "Reading")
                        .WithOne("ReadingBook")
                        .HasForeignKey("Shared.Models.Book", "ReadingId");

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("Shared.Models.Challenge", b =>
                {
                    b.HasOne("Shared.Models.User", "User")
                        .WithMany("Challenges")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.FileEntity", b =>
                {
                    b.HasOne("Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.Goal", b =>
                {
                    b.HasOne("Shared.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.Habit", b =>
                {
                    b.HasOne("Shared.Models.User", "AcquiredUser")
                        .WithMany("AcquiredHabits")
                        .HasForeignKey("AcquiredUserId");

                    b.HasOne("Shared.Models.User", "NegativeUser")
                        .WithOne("NegativeHabit")
                        .HasForeignKey("Shared.Models.Habit", "NegativeUserId");

                    b.HasOne("Shared.Models.User", "OvercomeNegativeUser")
                        .WithMany("OvercomeNegativeHabits")
                        .HasForeignKey("OvercomeNegativeUserId");

                    b.HasOne("Shared.Models.User", "PositiveUser")
                        .WithMany("PositiveHabits")
                        .HasForeignKey("PositiveUserId");

                    b.Navigation("AcquiredUser");

                    b.Navigation("NegativeUser");

                    b.Navigation("OvercomeNegativeUser");

                    b.Navigation("PositiveUser");
                });

            modelBuilder.Entity("Shared.Models.Notice", b =>
                {
                    b.HasOne("Shared.Models.Goal", "Goal")
                        .WithMany("Plan")
                        .HasForeignKey("GoalId");

                    b.HasOne("Shared.Models.Habit", "Habit")
                        .WithOne("Notice")
                        .HasForeignKey("Shared.Models.Notice", "HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.NoticeRepeat", "Repeat")
                        .WithMany("Notices")
                        .HasForeignKey("RepeatId");

                    b.Navigation("Goal");

                    b.Navigation("Habit");

                    b.Navigation("Repeat");
                });

            modelBuilder.Entity("Shared.Models.NoticeRepeat", b =>
                {
                    b.HasOne("Shared.Models.BuiltInFrequency", "BuiltInFrequency")
                        .WithMany("Repeats")
                        .HasForeignKey("BuiltInFrequencyId");

                    b.HasOne("Shared.Models.EndRepeat", "EndRepeat")
                        .WithMany("Repeats")
                        .HasForeignKey("EndRepeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.UserFrequency", "UserFrequency")
                        .WithMany("Repeats")
                        .HasForeignKey("UserFrequencyId");

                    b.Navigation("BuiltInFrequency");

                    b.Navigation("EndRepeat");

                    b.Navigation("UserFrequency");
                });

            modelBuilder.Entity("Shared.Models.Rd71", b =>
                {
                    b.HasOne("Shared.Models.Challenge", "Challenge")
                        .WithOne("Rd71")
                        .HasForeignKey("Shared.Models.Rd71", "ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Diet", "Diet")
                        .WithMany("Rd71s")
                        .HasForeignKey("DietId");

                    b.HasOne("Shared.Models.Reading", "Reading")
                        .WithOne("Rd71")
                        .HasForeignKey("Shared.Models.Rd71", "ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.UserTask", "UserTask")
                        .WithMany("Rd71s")
                        .HasForeignKey("UserTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Workout", "Workout")
                        .WithMany("Rd71s")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Diet");

                    b.Navigation("Reading");

                    b.Navigation("UserTask");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Shared.Models.TimeZone", b =>
                {
                    b.HasOne("Shared.Models.Notice", "Notice")
                        .WithOne("TimeZone")
                        .HasForeignKey("Shared.Models.TimeZone", "NoticeId");

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("Shared.Models.TrainingProgram", b =>
                {
                    b.HasOne("Shared.Models.Workout", "Workout")
                        .WithMany("AvailableTrainingPrograms")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.HasOne("Shared.Models.DevelopmentPlan", "DevelopmentPlan")
                        .WithMany("UsersWhichUseThis")
                        .HasForeignKey("DevelopmentPlanId");

                    b.Navigation("DevelopmentPlan");
                });

            modelBuilder.Entity("Shared.Models.BuiltInFrequency", b =>
                {
                    b.Navigation("Repeats");
                });

            modelBuilder.Entity("Shared.Models.Challenge", b =>
                {
                    b.Navigation("Rd71");
                });

            modelBuilder.Entity("Shared.Models.DevelopmentPlan", b =>
                {
                    b.Navigation("UsersWhichUseThis");
                });

            modelBuilder.Entity("Shared.Models.Diet", b =>
                {
                    b.Navigation("Rd71s");
                });

            modelBuilder.Entity("Shared.Models.EndRepeat", b =>
                {
                    b.Navigation("Repeats");
                });

            modelBuilder.Entity("Shared.Models.Goal", b =>
                {
                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Shared.Models.Habit", b =>
                {
                    b.Navigation("Notice");
                });

            modelBuilder.Entity("Shared.Models.Notice", b =>
                {
                    b.Navigation("TimeZone");
                });

            modelBuilder.Entity("Shared.Models.NoticeRepeat", b =>
                {
                    b.Navigation("Notices");
                });

            modelBuilder.Entity("Shared.Models.Reading", b =>
                {
                    b.Navigation("Rd71");

                    b.Navigation("ReadingBook");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Navigation("AcquiredHabits");

                    b.Navigation("Challenges");

                    b.Navigation("Goals");

                    b.Navigation("NegativeHabit");

                    b.Navigation("OvercomeNegativeHabits");

                    b.Navigation("PositiveHabits");
                });

            modelBuilder.Entity("Shared.Models.UserFrequency", b =>
                {
                    b.Navigation("Repeats");
                });

            modelBuilder.Entity("Shared.Models.UserTask", b =>
                {
                    b.Navigation("Rd71s");
                });

            modelBuilder.Entity("Shared.Models.Workout", b =>
                {
                    b.Navigation("AvailableTrainingPrograms");

                    b.Navigation("Rd71s");
                });
#pragma warning restore 612, 618
        }
    }
}
