// <auto-generated />
using System;
using SET.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SET.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211215220758_AddPropUserStatusInChallengeToChallangeModel")]
    partial class AddPropUserStatusInChallengeToChallangeModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookReading", b =>
                {
                    b.Property<Guid>("ReadBooksDuringChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReadingFinishedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReadBooksDuringChallengeId", "ReadingFinishedId");

                    b.HasIndex("ReadingFinishedId");

                    b.ToTable("BookReading");
                });

            modelBuilder.Entity("DietRecipe", b =>
                {
                    b.Property<Guid>("FitDietsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FitDietsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("DietRecipe");
                });

            modelBuilder.Entity("NoticeReminder", b =>
                {
                    b.Property<Guid>("NoticesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RemindersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NoticesId", "RemindersId");

                    b.HasIndex("RemindersId");

                    b.ToTable("NoticeReminder");
                });

            modelBuilder.Entity("PersonalPrincipleUser", b =>
                {
                    b.Property<Guid>("PersonalPrinciplesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonalPrinciplesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("PersonalPrincipleUser");
                });

            modelBuilder.Entity("Shared.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TimesRead")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReadingId")
                        .IsUnique()
                        .HasFilter("[ReadingId] IS NOT NULL");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Shared.Models.BuiltInFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BuiltInFrequencies");
                });

            modelBuilder.Entity("Shared.Models.Challanges.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChallangeName")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlWithFullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserStatusInChallenge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("Shared.Models.DevelopmentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DevelopmentPlanType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DevelopmentPlans");
                });

            modelBuilder.Entity("Shared.Models.Diet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diets");
                });

            modelBuilder.Entity("Shared.Models.EndRepeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Never")
                        .HasColumnType("bit");

                    b.Property<int?>("Timer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EndRepeats");
                });

            modelBuilder.Entity("Shared.Models.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilePurpose")
                        .HasColumnType("int");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FileEntities");
                });

            modelBuilder.Entity("Shared.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityArea")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonToAchieve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Shared.Models.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcquiredUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityArea")
                        .HasColumnType("int");

                    b.Property<int>("DaysCountToAchieve")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NegativeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OvercomeNegativeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PositiveUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimesCountExecutedAct")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfHabit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcquiredUserId");

                    b.HasIndex("NegativeUserId")
                        .IsUnique()
                        .HasFilter("[NegativeUserId] IS NOT NULL");

                    b.HasIndex("OvercomeNegativeUserId");

                    b.HasIndex("PositiveUserId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("Shared.Models.Notice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("From")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RepeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("HabitId")
                        .IsUnique();

                    b.HasIndex("RepeatId");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("Shared.Models.NoticeRepeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuiltInFrequencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EndRepeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserFrequencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuiltInFrequencyId");

                    b.HasIndex("EndRepeatId");

                    b.HasIndex("UserFrequencyId");

                    b.ToTable("NoticeRepeats");
                });

            modelBuilder.Entity("Shared.Models.PersonalPrinciple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonToFollow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonalPrinciples");
                });

            modelBuilder.Entity("Shared.Models.Rd71", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletedDays")
                        .HasColumnType("int");

                    b.Property<Guid?>("DietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEasyVersion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MinTimeWorkoutExecute")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DietId");

                    b.HasIndex("ReadingId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserTaskId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Rd71s");
                });

            modelBuilder.Entity("Shared.Models.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("Shared.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Shared.Models.RecomendedBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecomendedBooks");
                });

            modelBuilder.Entity("Shared.Models.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("TimeToMainNotice")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Shared.Models.Statement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1173c65d-908b-40d4-a88e-4d80f696eb09"),
                            Author = "Albert Einstein",
                            Text = "We cannot solve problems with the kind of thinking we employed when we came up with them."
                        },
                        new
                        {
                            Id = new Guid("ed2147a2-1913-4936-8bab-22874c026082"),
                            Author = "Mahatma Gandhi",
                            Text = "Learn as if you will live forever, live like you will die tomorrow."
                        },
                        new
                        {
                            Id = new Guid("3f4b3d37-4248-4342-9c0a-9399fc388834"),
                            Author = "Mark Twain",
                            Text = "Stay away from those people who try to disparage your ambitions. Small minds will always do that, but great minds will give you a feeling that you can become great too."
                        },
                        new
                        {
                            Id = new Guid("baf40992-ea91-4bdc-b9ae-9490d2b4f892"),
                            Author = "Eleanor Roosevelt",
                            Text = "When you give joy to other people, you get more joy in return. You should give a good thought to happiness that you can give out."
                        },
                        new
                        {
                            Id = new Guid("3281ee84-b166-4f58-b3a2-dcdf832a1d8c"),
                            Author = "Norman Vincent Peale",
                            Text = "When you change your thoughts, remember to also change your world."
                        },
                        new
                        {
                            Id = new Guid("cb5f50b7-0df5-4678-8880-98bf70e9cbe2"),
                            Author = "Walter Anderson",
                            Text = "It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest."
                        },
                        new
                        {
                            Id = new Guid("a07c9c3e-07b6-42e3-9210-e59607b40c1f"),
                            Author = "Diane McLaren",
                            Text = "Nature has given us all the pieces required to achieve exceptional wellness and health, but has left it to us to put these pieces together."
                        },
                        new
                        {
                            Id = new Guid("28e1ad79-cbcd-4a20-a886-a15ca6695bbc"),
                            Author = "Alexander Graham Bell",
                            Text = "Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus."
                        },
                        new
                        {
                            Id = new Guid("d5d0f894-9e58-4ebc-84ce-24c425380506"),
                            Author = "Jim Rohn",
                            Text = "Either you run the day or the day runs you."
                        },
                        new
                        {
                            Id = new Guid("a8e8ecca-30a0-4d70-a275-aecf919994fa"),
                            Author = "Thomas Jefferson",
                            Text = "I’m a greater believer in luck, and I find the harder I work the more I have of it."
                        },
                        new
                        {
                            Id = new Guid("5887ff8a-b452-414c-9628-b105710323ea"),
                            Author = "Paulo Coelho",
                            Text = "When we strive to become better than we are, everything around us becomes better too."
                        },
                        new
                        {
                            Id = new Guid("0e846001-d1d5-4990-ba8f-c8c4213e6618"),
                            Author = "Thomas Edison",
                            Text = "Opportunity is missed by most people because it is dressed in overalls and looks like work."
                        },
                        new
                        {
                            Id = new Guid("53555d1b-ade2-4e0f-a3f2-083a2de28e5f"),
                            Author = "Tony Robbins",
                            Text = "Setting goals is the first step in turning the invisible into the visible."
                        },
                        new
                        {
                            Id = new Guid("f0fc36d4-f681-4e17-86f6-2b3fa109e564"),
                            Author = "Steve Jobs",
                            Text = "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it."
                        },
                        new
                        {
                            Id = new Guid("8bd3639d-c1cc-431d-a378-ddecb09ef529"),
                            Author = "Alexandra of The Productivity Zone",
                            Text = "It’s not about better time management. It’s about better life management"
                        },
                        new
                        {
                            Id = new Guid("d4ee520d-3d2b-4c6e-9290-dbea5cdbc2be"),
                            Author = "Winston Churchill",
                            Text = "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty."
                        },
                        new
                        {
                            Id = new Guid("ad908b5d-c70d-4e3a-91fc-38978b3ce774"),
                            Author = "Will Rogers",
                            Text = "Don’t let yesterday take up too much of today."
                        },
                        new
                        {
                            Id = new Guid("a33725e8-cc23-404c-9c90-f11bfccf1f5f"),
                            Text = "You learn more from failure than from success. Don’t let it stop you. Failure builds character."
                        },
                        new
                        {
                            Id = new Guid("7e4e5e3f-b6d8-428d-bf7e-db9ab988b699"),
                            Author = "Steve Jobs",
                            Text = "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you."
                        },
                        new
                        {
                            Id = new Guid("69b6bbe0-3326-4a5a-9d45-fd09e4d612c7"),
                            Author = "Vernon Sanders Law",
                            Text = "Experience is a hard teacher because she gives the test first, the lesson afterwards."
                        },
                        new
                        {
                            Id = new Guid("87ecc852-a9d8-4927-93ec-34330c625470"),
                            Author = "Dorothy West",
                            Text = "To know how much there is to know is the beginning of learning to live."
                        },
                        new
                        {
                            Id = new Guid("0459f3bb-f7de-4099-bcf3-2b20d9d16195"),
                            Author = "Tony Robbins",
                            Text = "Goal setting is the secret to a compelling future."
                        },
                        new
                        {
                            Id = new Guid("c69ed654-ebc2-486d-a60b-efd0422d0fa9"),
                            Author = "Dalai Lama",
                            Text = "Just one small positive thought in the morning can change your whole day."
                        },
                        new
                        {
                            Id = new Guid("48efb3cc-1654-44bf-bf11-69d00614a078"),
                            Author = "Chris Grosser",
                            Text = "Opportunities don't happen, you create them."
                        },
                        new
                        {
                            Id = new Guid("6dae8e27-eba4-4081-9ee7-5e4d3aa69ae7"),
                            Author = "Gary Vaynerchuk",
                            Text = "Love your family, work super hard, live your passion."
                        },
                        new
                        {
                            Id = new Guid("249c20dc-43f3-4a44-8393-1bbd16c852ad"),
                            Author = "George Eliot",
                            Text = "It is never too late to be what you might have been."
                        },
                        new
                        {
                            Id = new Guid("85d5b23f-14c0-4e8e-9fb5-cb85d6687628"),
                            Author = "Les Brown",
                            Text = "Don't let someone else's opinion of you become your reality"
                        },
                        new
                        {
                            Id = new Guid("1d07e331-e72d-4266-9e89-d9ce27409bf1"),
                            Author = "Mark Cuban",
                            Text = "If you’re not positive energy, you’re negative energy."
                        },
                        new
                        {
                            Id = new Guid("7c39cb5e-9a32-41c2-86f5-d96fc075b1e1"),
                            Author = "Stephen R. Covey",
                            Text = "I am not a product of my circumstances. I am a product of my decisions."
                        },
                        new
                        {
                            Id = new Guid("fa9c0897-f923-41d6-b73f-156ff240b577"),
                            Author = "Arlan Hamilton",
                            Text = "I can’t tell you how many times I’ve been given a no. Only to find that a better, brighter, bigger yes was right around the corner."
                        },
                        new
                        {
                            Id = new Guid("ebcda77a-2b50-4cb9-a3b8-2b4367ce256d"),
                            Author = "Mark Twain",
                            Text = "The two most important days in your life are the day you’re born and the day you find out why."
                        },
                        new
                        {
                            Id = new Guid("d7777d68-6441-4599-883b-a9eaecf5a79d"),
                            Author = "Pema Chodron",
                            Text = "Nothing ever goes away until it teaches us what we need to know."
                        },
                        new
                        {
                            Id = new Guid("d5aa8bd1-c4b3-4a6d-aa4a-4ff04b7d355c"),
                            Author = "Bruce Lee",
                            Text = "We can see through others only when we can see through ourselves."
                        },
                        new
                        {
                            Id = new Guid("1afd05c3-2064-4fd2-bd5c-5108b3eee117"),
                            Author = "Robert Frost",
                            Text = "The best way out is always through."
                        },
                        new
                        {
                            Id = new Guid("4e9cd71b-a97b-4bff-95ed-51b8909be566"),
                            Author = "Frederick Douglass",
                            Text = "If there is no struggle, there is no progress."
                        },
                        new
                        {
                            Id = new Guid("a424f578-fc05-4757-b6c0-9ade7c49566f"),
                            Author = "Ruth Gordo",
                            Text = "Courage is like a muscle. We strengthen it by use"
                        },
                        new
                        {
                            Id = new Guid("e03bc51b-b588-4065-aa75-3fdee655c47c"),
                            Author = "Cormac McCarthy",
                            Text = "Keep a little fire burning; however small, however hidden."
                        });
                });

            modelBuilder.Entity("Shared.Models.TimeZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NoticeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NoticeId")
                        .IsUnique()
                        .HasFilter("[NoticeId] IS NOT NULL");

                    b.ToTable("TimeZones");
                });

            modelBuilder.Entity("Shared.Models.TrainingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeExecuteForOneTraining")
                        .HasColumnType("time");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DevelopmentPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentPlanId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shared.Models.UserFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Frequency")
                        .HasColumnType("time");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserFrequencies");
                });

            modelBuilder.Entity("Shared.Models.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityArea")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("Shared.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("BookReading", b =>
                {
                    b.HasOne("Shared.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("ReadBooksDuringChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Reading", null)
                        .WithMany()
                        .HasForeignKey("ReadingFinishedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DietRecipe", b =>
                {
                    b.HasOne("Shared.Models.Diet", null)
                        .WithMany()
                        .HasForeignKey("FitDietsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoticeReminder", b =>
                {
                    b.HasOne("Shared.Models.Notice", null)
                        .WithMany()
                        .HasForeignKey("NoticesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Reminder", null)
                        .WithMany()
                        .HasForeignKey("RemindersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalPrincipleUser", b =>
                {
                    b.HasOne("Shared.Models.PersonalPrinciple", null)
                        .WithMany()
                        .HasForeignKey("PersonalPrinciplesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Book", b =>
                {
                    b.HasOne("Shared.Models.Reading", "Reading")
                        .WithOne("ReadingBook")
                        .HasForeignKey("Shared.Models.Book", "ReadingId");

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("Shared.Models.FileEntity", b =>
                {
                    b.HasOne("Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.Goal", b =>
                {
                    b.HasOne("Shared.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.Habit", b =>
                {
                    b.HasOne("Shared.Models.User", "AcquiredUser")
                        .WithMany("AcquiredHabits")
                        .HasForeignKey("AcquiredUserId");

                    b.HasOne("Shared.Models.User", "NegativeUser")
                        .WithOne("NegativeHabit")
                        .HasForeignKey("Shared.Models.Habit", "NegativeUserId");

                    b.HasOne("Shared.Models.User", "OvercomeNegativeUser")
                        .WithMany("OvercomeNegativeHabits")
                        .HasForeignKey("OvercomeNegativeUserId");

                    b.HasOne("Shared.Models.User", "PositiveUser")
                        .WithMany("PositiveHabits")
                        .HasForeignKey("PositiveUserId");

                    b.Navigation("AcquiredUser");

                    b.Navigation("NegativeUser");

                    b.Navigation("OvercomeNegativeUser");

                    b.Navigation("PositiveUser");
                });

            modelBuilder.Entity("Shared.Models.Notice", b =>
                {
                    b.HasOne("Shared.Models.Goal", "Goal")
                        .WithMany("Plan")
                        .HasForeignKey("GoalId");

                    b.HasOne("Shared.Models.Habit", "Habit")
                        .WithOne("Notice")
                        .HasForeignKey("Shared.Models.Notice", "HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.NoticeRepeat", "Repeat")
                        .WithMany("Notices")
                        .HasForeignKey("RepeatId");

                    b.Navigation("Goal");

                    b.Navigation("Habit");

                    b.Navigation("Repeat");
                });

            modelBuilder.Entity("Shared.Models.NoticeRepeat", b =>
                {
                    b.HasOne("Shared.Models.BuiltInFrequency", "BuiltInFrequency")
                        .WithMany("Repeats")
                        .HasForeignKey("BuiltInFrequencyId");

                    b.HasOne("Shared.Models.EndRepeat", "EndRepeat")
                        .WithMany("Repeats")
                        .HasForeignKey("EndRepeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.UserFrequency", "UserFrequency")
                        .WithMany("Repeats")
                        .HasForeignKey("UserFrequencyId");

                    b.Navigation("BuiltInFrequency");

                    b.Navigation("EndRepeat");

                    b.Navigation("UserFrequency");
                });

            modelBuilder.Entity("Shared.Models.Rd71", b =>
                {
                    b.HasOne("Shared.Models.Diet", "Diet")
                        .WithMany("Rd71s")
                        .HasForeignKey("DietId");

                    b.HasOne("Shared.Models.Reading", "Reading")
                        .WithOne("Rd71")
                        .HasForeignKey("Shared.Models.Rd71", "ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.User", "User")
                        .WithMany("Rd71s")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.UserTask", "UserTask")
                        .WithMany("Rd71s")
                        .HasForeignKey("UserTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Workout", "Workout")
                        .WithMany("Rd71s")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");

                    b.Navigation("Reading");

                    b.Navigation("User");

                    b.Navigation("UserTask");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Shared.Models.TimeZone", b =>
                {
                    b.HasOne("Shared.Models.Notice", "Notice")
                        .WithOne("TimeZone")
                        .HasForeignKey("Shared.Models.TimeZone", "NoticeId");

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("Shared.Models.TrainingProgram", b =>
                {
                    b.HasOne("Shared.Models.Workout", "Workout")
                        .WithMany("AvailableTrainingPrograms")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.HasOne("Shared.Models.DevelopmentPlan", "DevelopmentPlan")
                        .WithMany("UsersWhichUseThis")
                        .HasForeignKey("DevelopmentPlanId");

                    b.Navigation("DevelopmentPlan");
                });

            modelBuilder.Entity("Shared.Models.BuiltInFrequency", b =>
                {
                    b.Navigation("Repeats");
                });

            modelBuilder.Entity("Shared.Models.DevelopmentPlan", b =>
                {
                    b.Navigation("UsersWhichUseThis");
                });

            modelBuilder.Entity("Shared.Models.Diet", b =>
                {
                    b.Navigation("Rd71s");
                });

            modelBuilder.Entity("Shared.Models.EndRepeat", b =>
                {
                    b.Navigation("Repeats");
                });

            modelBuilder.Entity("Shared.Models.Goal", b =>
                {
                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Shared.Models.Habit", b =>
                {
                    b.Navigation("Notice");
                });

            modelBuilder.Entity("Shared.Models.Notice", b =>
                {
                    b.Navigation("TimeZone");
                });

            modelBuilder.Entity("Shared.Models.NoticeRepeat", b =>
                {
                    b.Navigation("Notices");
                });

            modelBuilder.Entity("Shared.Models.Reading", b =>
                {
                    b.Navigation("Rd71");

                    b.Navigation("ReadingBook");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Navigation("AcquiredHabits");

                    b.Navigation("Goals");

                    b.Navigation("NegativeHabit");

                    b.Navigation("OvercomeNegativeHabits");

                    b.Navigation("PositiveHabits");

                    b.Navigation("Rd71s");
                });

            modelBuilder.Entity("Shared.Models.UserFrequency", b =>
                {
                    b.Navigation("Repeats");
                });

            modelBuilder.Entity("Shared.Models.UserTask", b =>
                {
                    b.Navigation("Rd71s");
                });

            modelBuilder.Entity("Shared.Models.Workout", b =>
                {
                    b.Navigation("AvailableTrainingPrograms");

                    b.Navigation("Rd71s");
                });
#pragma warning restore 612, 618
        }
    }
}
