// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SET.DataAccess;

#nullable disable

namespace SET.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230911172641_AddRelationshipBetweenUserPrinciplesAndFrequencies")]
    partial class AddRelationshipBetweenUserPrinciplesAndFrequencies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookReading", b =>
                {
                    b.Property<Guid>("ReadBooksDuringChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReadingFinishedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReadBooksDuringChallengeId", "ReadingFinishedId");

                    b.HasIndex("ReadingFinishedId");

                    b.ToTable("BookReading");
                });

            modelBuilder.Entity("DietRecipe", b =>
                {
                    b.Property<Guid>("FitDietsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FitDietsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("DietRecipe");
                });

            modelBuilder.Entity("NoticeReminder", b =>
                {
                    b.Property<Guid>("NoticesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RemindersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NoticesId", "RemindersId");

                    b.HasIndex("RemindersId");

                    b.ToTable("NoticeReminder");
                });

            modelBuilder.Entity("SET.Shared.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TimesRead")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReadingId")
                        .IsUnique()
                        .HasFilter("[ReadingId] IS NOT NULL");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("SET.Shared.Models.BuiltInFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BuiltInFrequencies");
                });

            modelBuilder.Entity("SET.Shared.Models.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Foundator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlWithFullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserStatusInChallenge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("SET.Shared.Models.ComplicatedDevProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("ComplicatedDevPrograms", "dev");
                });

            modelBuilder.Entity("SET.Shared.Models.DevProgramProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ChangedInPercent")
                        .HasColumnType("decimal(11, 8)");

                    b.Property<decimal>("TotalPrinciplesProgress")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal>("TotalProgressOfGoals")
                        .HasColumnType("decimal(18, 8)");

                    b.HasKey("Id");

                    b.ToTable("DevProgramsProgresses", "dev");
                });

            modelBuilder.Entity("SET.Shared.Models.DevelopmentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DevelopmentPlanType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DevelopmentPlans");
                });

            modelBuilder.Entity("SET.Shared.Models.Diet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diets");
                });

            modelBuilder.Entity("SET.Shared.Models.EndRepeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Never")
                        .HasColumnType("bit");

                    b.Property<int?>("Timer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EndRepeats");
                });

            modelBuilder.Entity("SET.Shared.Models.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilePurpose")
                        .HasColumnType("int");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FileEntities");
                });

            modelBuilder.Entity("SET.Shared.Models.Frequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Frequencies", "ntc");
                });

            modelBuilder.Entity("SET.Shared.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityArea")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonToAchieve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("SET.Shared.Models.Notice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("From")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RepeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("RepeatId");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("SET.Shared.Models.NoticeRepeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuiltInFrequencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EndRepeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserFrequencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuiltInFrequencyId");

                    b.HasIndex("EndRepeatId");

                    b.HasIndex("UserFrequencyId");

                    b.ToTable("NoticeRepeats");
                });

            modelBuilder.Entity("SET.Shared.Models.Rd71", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletedDays")
                        .HasColumnType("int");

                    b.Property<Guid?>("DietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEasyVersion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MinTimeWorkoutExecute")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId")
                        .IsUnique();

                    b.HasIndex("DietId");

                    b.HasIndex("ReadingId")
                        .IsUnique();

                    b.HasIndex("UserTaskId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Rd71s");
                });

            modelBuilder.Entity("SET.Shared.Models.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("SET.Shared.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("SET.Shared.Models.RecomendedBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecomendedBooks");
                });

            modelBuilder.Entity("SET.Shared.Models.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("TimeToMainNotice")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("SET.Shared.Models.Statement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statements");
                });

            modelBuilder.Entity("SET.Shared.Models.TimeZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NoticeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NoticeId")
                        .IsUnique()
                        .HasFilter("[NoticeId] IS NOT NULL");

                    b.ToTable("TimeZones");
                });

            modelBuilder.Entity("SET.Shared.Models.TrainingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeExecuteForOneTraining")
                        .HasColumnType("time");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("SET.Shared.Models.TypeOfComplicatedDevProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TypeOfComplicatedDevProgram");
                });

            modelBuilder.Entity("SET.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DevelopmentPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("MainSlogan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varbinary");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentPlanId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLife", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<double?>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("UserAreasOfLife", "arlf");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLifeUserPrinciple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaOfLifeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrincipleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PriorityOfPrinciple")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaOfLifeId");

                    b.HasIndex("PrincipleId");

                    b.ToTable("UserAreasOfLifeUserPrinciples", "arlf");
                });

            modelBuilder.Entity("SET.Shared.Models.UserFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Frequency")
                        .HasColumnType("time");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserFrequencies");
                });

            modelBuilder.Entity("SET.Shared.Models.UserPrinciple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FrequencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsShownInProgressTab")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("PercentageAchieved")
                        .HasColumnType("decimal(8, 5)");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonToFollow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FrequencyId");

                    b.ToTable("UserPrinciples", "prc");
                });

            modelBuilder.Entity("SET.Shared.Models.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityArea")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("SET.Shared.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("UserPrincipleUserPrinciple", b =>
                {
                    b.Property<Guid>("ParentPrinciplesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubPrinciplesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ParentPrinciplesId", "SubPrinciplesId");

                    b.HasIndex("SubPrinciplesId");

                    b.ToTable("UserPrincipleUserPrinciple", "prc");
                });

            modelBuilder.Entity("BookReading", b =>
                {
                    b.HasOne("SET.Shared.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("ReadBooksDuringChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.Reading", null)
                        .WithMany()
                        .HasForeignKey("ReadingFinishedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DietRecipe", b =>
                {
                    b.HasOne("SET.Shared.Models.Diet", null)
                        .WithMany()
                        .HasForeignKey("FitDietsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoticeReminder", b =>
                {
                    b.HasOne("SET.Shared.Models.Notice", null)
                        .WithMany()
                        .HasForeignKey("NoticesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.Reminder", null)
                        .WithMany()
                        .HasForeignKey("RemindersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SET.Shared.Models.Book", b =>
                {
                    b.HasOne("SET.Shared.Models.Reading", "Reading")
                        .WithOne("ReadingBook")
                        .HasForeignKey("SET.Shared.Models.Book", "ReadingId");

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("SET.Shared.Models.Challenge", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany("Challenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.ComplicatedDevProgram", b =>
                {
                    b.HasOne("SET.Shared.Models.TypeOfComplicatedDevProgram", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SET.Shared.Models.FileEntity", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.Goal", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.Notice", b =>
                {
                    b.HasOne("SET.Shared.Models.Goal", "Goal")
                        .WithMany("Plan")
                        .HasForeignKey("GoalId");

                    b.HasOne("SET.Shared.Models.NoticeRepeat", "Repeat")
                        .WithMany("Notices")
                        .HasForeignKey("RepeatId");

                    b.Navigation("Goal");

                    b.Navigation("Repeat");
                });

            modelBuilder.Entity("SET.Shared.Models.NoticeRepeat", b =>
                {
                    b.HasOne("SET.Shared.Models.BuiltInFrequency", "BuiltInFrequency")
                        .WithMany("Repeats")
                        .HasForeignKey("BuiltInFrequencyId");

                    b.HasOne("SET.Shared.Models.EndRepeat", "EndRepeat")
                        .WithMany("Repeats")
                        .HasForeignKey("EndRepeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.UserFrequency", "UserFrequency")
                        .WithMany("Repeats")
                        .HasForeignKey("UserFrequencyId");

                    b.Navigation("BuiltInFrequency");

                    b.Navigation("EndRepeat");

                    b.Navigation("UserFrequency");
                });

            modelBuilder.Entity("SET.Shared.Models.Rd71", b =>
                {
                    b.HasOne("SET.Shared.Models.Challenge", "Challenge")
                        .WithOne("Rd71")
                        .HasForeignKey("SET.Shared.Models.Rd71", "ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.Diet", "Diet")
                        .WithMany("Rd71s")
                        .HasForeignKey("DietId");

                    b.HasOne("SET.Shared.Models.Reading", "Reading")
                        .WithOne("Rd71")
                        .HasForeignKey("SET.Shared.Models.Rd71", "ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.UserTask", "UserTask")
                        .WithMany("Rd71s")
                        .HasForeignKey("UserTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.Workout", "Workout")
                        .WithMany("Rd71s")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Diet");

                    b.Navigation("Reading");

                    b.Navigation("UserTask");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("SET.Shared.Models.TimeZone", b =>
                {
                    b.HasOne("SET.Shared.Models.Notice", "Notice")
                        .WithOne("TimeZone")
                        .HasForeignKey("SET.Shared.Models.TimeZone", "NoticeId");

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("SET.Shared.Models.TrainingProgram", b =>
                {
                    b.HasOne("SET.Shared.Models.Workout", "Workout")
                        .WithMany("AvailableTrainingPrograms")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("SET.Shared.Models.User", b =>
                {
                    b.HasOne("SET.Shared.Models.DevelopmentPlan", "DevelopmentPlan")
                        .WithMany("UsersWhichUseThis")
                        .HasForeignKey("DevelopmentPlanId");

                    b.Navigation("DevelopmentPlan");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLifeUserPrinciple", b =>
                {
                    b.HasOne("SET.Shared.Models.UserAreaOfLife", "AreaOfLife")
                        .WithMany("Principles")
                        .HasForeignKey("AreaOfLifeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.UserPrinciple", "Principle")
                        .WithMany("AreasOfLife")
                        .HasForeignKey("PrincipleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaOfLife");

                    b.Navigation("Principle");
                });

            modelBuilder.Entity("SET.Shared.Models.UserPrinciple", b =>
                {
                    b.HasOne("SET.Shared.Models.Frequency", "Frequency")
                        .WithMany("Principles")
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Frequency");
                });

            modelBuilder.Entity("UserPrincipleUserPrinciple", b =>
                {
                    b.HasOne("SET.Shared.Models.UserPrinciple", null)
                        .WithMany()
                        .HasForeignKey("ParentPrinciplesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.UserPrinciple", null)
                        .WithMany()
                        .HasForeignKey("SubPrinciplesId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SET.Shared.Models.BuiltInFrequency", b =>
                {
                    b.Navigation("Repeats");
                });

            modelBuilder.Entity("SET.Shared.Models.Challenge", b =>
                {
                    b.Navigation("Rd71");
                });

            modelBuilder.Entity("SET.Shared.Models.DevelopmentPlan", b =>
                {
                    b.Navigation("UsersWhichUseThis");
                });

            modelBuilder.Entity("SET.Shared.Models.Diet", b =>
                {
                    b.Navigation("Rd71s");
                });

            modelBuilder.Entity("SET.Shared.Models.EndRepeat", b =>
                {
                    b.Navigation("Repeats");
                });

            modelBuilder.Entity("SET.Shared.Models.Frequency", b =>
                {
                    b.Navigation("Principles");
                });

            modelBuilder.Entity("SET.Shared.Models.Goal", b =>
                {
                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SET.Shared.Models.Notice", b =>
                {
                    b.Navigation("TimeZone");
                });

            modelBuilder.Entity("SET.Shared.Models.NoticeRepeat", b =>
                {
                    b.Navigation("Notices");
                });

            modelBuilder.Entity("SET.Shared.Models.Reading", b =>
                {
                    b.Navigation("Rd71");

                    b.Navigation("ReadingBook");
                });

            modelBuilder.Entity("SET.Shared.Models.User", b =>
                {
                    b.Navigation("Challenges");

                    b.Navigation("Goals");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLife", b =>
                {
                    b.Navigation("Principles");
                });

            modelBuilder.Entity("SET.Shared.Models.UserFrequency", b =>
                {
                    b.Navigation("Repeats");
                });

            modelBuilder.Entity("SET.Shared.Models.UserPrinciple", b =>
                {
                    b.Navigation("AreasOfLife");
                });

            modelBuilder.Entity("SET.Shared.Models.UserTask", b =>
                {
                    b.Navigation("Rd71s");
                });

            modelBuilder.Entity("SET.Shared.Models.Workout", b =>
                {
                    b.Navigation("AvailableTrainingPrograms");

                    b.Navigation("Rd71s");
                });
#pragma warning restore 612, 618
        }
    }
}
