// <auto-generated />
using System;
using SET.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SET.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230607060321_ChangePasswordColumnToVarBinaryInUserTable")]
    partial class ChangePasswordColumnToVarBinaryInUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookReading", b =>
                {
                    b.Property<Guid>("ReadBooksDuringChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReadingFinishedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReadBooksDuringChallengeId", "ReadingFinishedId");

                    b.HasIndex("ReadingFinishedId");

                    b.ToTable("BookReading");
                });

            modelBuilder.Entity("DietRecipe", b =>
                {
                    b.Property<Guid>("FitDietsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FitDietsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("DietRecipe");
                });

            modelBuilder.Entity("NoticeReminder", b =>
                {
                    b.Property<Guid>("NoticesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RemindersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NoticesId", "RemindersId");

                    b.HasIndex("RemindersId");

                    b.ToTable("NoticeReminder");
                });

            modelBuilder.Entity("PersonalPrincipleUser", b =>
                {
                    b.Property<Guid>("PersonalPrinciplesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonalPrinciplesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("PersonalPrincipleUser");
                });

            modelBuilder.Entity("Shared.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TimesRead")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReadingId")
                        .IsUnique()
                        .HasFilter("[ReadingId] IS NOT NULL");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Shared.Models.BuiltInFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BuiltInFrequencies");
                });

            modelBuilder.Entity("Shared.Models.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Foundator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlWithFullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserStatusInChallenge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("Shared.Models.DevelopmentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DevelopmentPlanType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DevelopmentPlans");
                });

            modelBuilder.Entity("Shared.Models.Diet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diets");
                });

            modelBuilder.Entity("Shared.Models.EndRepeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Never")
                        .HasColumnType("bit");

                    b.Property<int?>("Timer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EndRepeats");
                });

            modelBuilder.Entity("Shared.Models.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilePurpose")
                        .HasColumnType("int");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FileEntities");
                });

            modelBuilder.Entity("Shared.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityArea")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonToAchieve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Shared.Models.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcquiredUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityArea")
                        .HasColumnType("int");

                    b.Property<int>("DaysCountToAchieve")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NegativeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OvercomeNegativeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PositiveUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimesCountExecutedAct")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfHabit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcquiredUserId");

                    b.HasIndex("NegativeUserId")
                        .IsUnique()
                        .HasFilter("[NegativeUserId] IS NOT NULL");

                    b.HasIndex("OvercomeNegativeUserId");

                    b.HasIndex("PositiveUserId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("Shared.Models.Notice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("From")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RepeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("HabitId")
                        .IsUnique();

                    b.HasIndex("RepeatId");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("Shared.Models.NoticeRepeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuiltInFrequencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EndRepeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserFrequencyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuiltInFrequencyId");

                    b.HasIndex("EndRepeatId");

                    b.HasIndex("UserFrequencyId");

                    b.ToTable("NoticeRepeats");
                });

            modelBuilder.Entity("Shared.Models.PersonalPrinciple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonToFollow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonalPrinciples");
                });

            modelBuilder.Entity("Shared.Models.Rd71", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletedDays")
                        .HasColumnType("int");

                    b.Property<Guid?>("DietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEasyVersion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MinTimeWorkoutExecute")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId")
                        .IsUnique();

                    b.HasIndex("DietId");

                    b.HasIndex("ReadingId")
                        .IsUnique();

                    b.HasIndex("UserTaskId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Rd71s");
                });

            modelBuilder.Entity("Shared.Models.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("Shared.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Shared.Models.RecomendedBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecomendedBooks");
                });

            modelBuilder.Entity("Shared.Models.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("TimeToMainNotice")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Shared.Models.Statement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statements");
                });

            modelBuilder.Entity("Shared.Models.TimeZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NoticeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NoticeId")
                        .IsUnique()
                        .HasFilter("[NoticeId] IS NOT NULL");

                    b.ToTable("TimeZones");
                });

            modelBuilder.Entity("Shared.Models.TrainingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeExecuteForOneTraining")
                        .HasColumnType("time");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DevelopmentPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varbinary");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentPlanId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shared.Models.UserFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Frequency")
                        .HasColumnType("time");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserFrequencies");
                });

            modelBuilder.Entity("Shared.Models.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityArea")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("Shared.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("BookReading", b =>
                {
                    b.HasOne("Shared.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("ReadBooksDuringChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Reading", null)
                        .WithMany()
                        .HasForeignKey("ReadingFinishedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DietRecipe", b =>
                {
                    b.HasOne("Shared.Models.Diet", null)
                        .WithMany()
                        .HasForeignKey("FitDietsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoticeReminder", b =>
                {
                    b.HasOne("Shared.Models.Notice", null)
                        .WithMany()
                        .HasForeignKey("NoticesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Reminder", null)
                        .WithMany()
                        .HasForeignKey("RemindersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalPrincipleUser", b =>
                {
                    b.HasOne("Shared.Models.PersonalPrinciple", null)
                        .WithMany()
                        .HasForeignKey("PersonalPrinciplesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Book", b =>
                {
                    b.HasOne("Shared.Models.Reading", "Reading")
                        .WithOne("ReadingBook")
                        .HasForeignKey("Shared.Models.Book", "ReadingId");

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("Shared.Models.Challenge", b =>
                {
                    b.HasOne("Shared.Models.User", "User")
                        .WithMany("Challenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.FileEntity", b =>
                {
                    b.HasOne("Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.Goal", b =>
                {
                    b.HasOne("Shared.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.Habit", b =>
                {
                    b.HasOne("Shared.Models.User", "AcquiredUser")
                        .WithMany("AcquiredHabits")
                        .HasForeignKey("AcquiredUserId");

                    b.HasOne("Shared.Models.User", "NegativeUser")
                        .WithOne("NegativeHabit")
                        .HasForeignKey("Shared.Models.Habit", "NegativeUserId");

                    b.HasOne("Shared.Models.User", "OvercomeNegativeUser")
                        .WithMany("OvercomeNegativeHabits")
                        .HasForeignKey("OvercomeNegativeUserId");

                    b.HasOne("Shared.Models.User", "PositiveUser")
                        .WithMany("PositiveHabits")
                        .HasForeignKey("PositiveUserId");

                    b.Navigation("AcquiredUser");

                    b.Navigation("NegativeUser");

                    b.Navigation("OvercomeNegativeUser");

                    b.Navigation("PositiveUser");
                });

            modelBuilder.Entity("Shared.Models.Notice", b =>
                {
                    b.HasOne("Shared.Models.Goal", "Goal")
                        .WithMany("Plan")
                        .HasForeignKey("GoalId");

                    b.HasOne("Shared.Models.Habit", "Habit")
                        .WithOne("Notice")
                        .HasForeignKey("Shared.Models.Notice", "HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.NoticeRepeat", "Repeat")
                        .WithMany("Notices")
                        .HasForeignKey("RepeatId");

                    b.Navigation("Goal");

                    b.Navigation("Habit");

                    b.Navigation("Repeat");
                });

            modelBuilder.Entity("Shared.Models.NoticeRepeat", b =>
                {
                    b.HasOne("Shared.Models.BuiltInFrequency", "BuiltInFrequency")
                        .WithMany("Repeats")
                        .HasForeignKey("BuiltInFrequencyId");

                    b.HasOne("Shared.Models.EndRepeat", "EndRepeat")
                        .WithMany("Repeats")
                        .HasForeignKey("EndRepeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.UserFrequency", "UserFrequency")
                        .WithMany("Repeats")
                        .HasForeignKey("UserFrequencyId");

                    b.Navigation("BuiltInFrequency");

                    b.Navigation("EndRepeat");

                    b.Navigation("UserFrequency");
                });

            modelBuilder.Entity("Shared.Models.Rd71", b =>
                {
                    b.HasOne("Shared.Models.Challenge", "Challenge")
                        .WithOne("Rd71")
                        .HasForeignKey("Shared.Models.Rd71", "ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Diet", "Diet")
                        .WithMany("Rd71s")
                        .HasForeignKey("DietId");

                    b.HasOne("Shared.Models.Reading", "Reading")
                        .WithOne("Rd71")
                        .HasForeignKey("Shared.Models.Rd71", "ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.UserTask", "UserTask")
                        .WithMany("Rd71s")
                        .HasForeignKey("UserTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.Workout", "Workout")
                        .WithMany("Rd71s")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Diet");

                    b.Navigation("Reading");

                    b.Navigation("UserTask");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Shared.Models.TimeZone", b =>
                {
                    b.HasOne("Shared.Models.Notice", "Notice")
                        .WithOne("TimeZone")
                        .HasForeignKey("Shared.Models.TimeZone", "NoticeId");

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("Shared.Models.TrainingProgram", b =>
                {
                    b.HasOne("Shared.Models.Workout", "Workout")
                        .WithMany("AvailableTrainingPrograms")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.HasOne("Shared.Models.DevelopmentPlan", "DevelopmentPlan")
                        .WithMany("UsersWhichUseThis")
                        .HasForeignKey("DevelopmentPlanId");

                    b.Navigation("DevelopmentPlan");
                });

            modelBuilder.Entity("Shared.Models.BuiltInFrequency", b =>
                {
                    b.Navigation("Repeats");
                });

            modelBuilder.Entity("Shared.Models.Challenge", b =>
                {
                    b.Navigation("Rd71");
                });

            modelBuilder.Entity("Shared.Models.DevelopmentPlan", b =>
                {
                    b.Navigation("UsersWhichUseThis");
                });

            modelBuilder.Entity("Shared.Models.Diet", b =>
                {
                    b.Navigation("Rd71s");
                });

            modelBuilder.Entity("Shared.Models.EndRepeat", b =>
                {
                    b.Navigation("Repeats");
                });

            modelBuilder.Entity("Shared.Models.Goal", b =>
                {
                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Shared.Models.Habit", b =>
                {
                    b.Navigation("Notice");
                });

            modelBuilder.Entity("Shared.Models.Notice", b =>
                {
                    b.Navigation("TimeZone");
                });

            modelBuilder.Entity("Shared.Models.NoticeRepeat", b =>
                {
                    b.Navigation("Notices");
                });

            modelBuilder.Entity("Shared.Models.Reading", b =>
                {
                    b.Navigation("Rd71");

                    b.Navigation("ReadingBook");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Navigation("AcquiredHabits");

                    b.Navigation("Challenges");

                    b.Navigation("Goals");

                    b.Navigation("NegativeHabit");

                    b.Navigation("OvercomeNegativeHabits");

                    b.Navigation("PositiveHabits");
                });

            modelBuilder.Entity("Shared.Models.UserFrequency", b =>
                {
                    b.Navigation("Repeats");
                });

            modelBuilder.Entity("Shared.Models.UserTask", b =>
                {
                    b.Navigation("Rd71s");
                });

            modelBuilder.Entity("Shared.Models.Workout", b =>
                {
                    b.Navigation("AvailableTrainingPrograms");

                    b.Navigation("Rd71s");
                });
#pragma warning restore 612, 618
        }
    }
}
