// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SET.DataAccess;

#nullable disable

namespace SET.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240511090412_RenamedSecondIdToIdForHabits")]
    partial class RenamedSecondIdToIdForHabits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("SQ_FilesEntity")
                .StartsAt(100L);

            modelBuilder.HasSequence("SQ_Frequencies")
                .StartsAt(100L);

            modelBuilder.HasSequence("SQ_ProgressesOfHabits")
                .StartsAt(100L);

            modelBuilder.HasSequence("SQ_UserAreasOfLife")
                .StartsAt(100L);

            modelBuilder.HasSequence("SQ_UserAreasOfLifeUserHabit")
                .StartsAt(100L);

            modelBuilder.HasSequence("SQ_UserHabits")
                .StartsAt(100L);

            modelBuilder.HasSequence("SQ_Users")
                .StartsAt(100L);

            modelBuilder.Entity("SET.Shared.Models.FileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR SQ_FilesEntity");

                    b.Property<string>("FileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilePurpose")
                        .HasColumnType("int");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FileEntities", "flt");
                });

            modelBuilder.Entity("SET.Shared.Models.Frequency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR SQ_Frequencies");

                    b.Property<int>("IntervalLengthInDays")
                        .HasColumnType("int");

                    b.Property<int>("Repeats")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(7, 6)");

                    b.HasKey("Id");

                    b.ToTable("Frequencies", "ntc");
                });

            modelBuilder.Entity("SET.Shared.Models.ProgressOfHabit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR SQ_ProgressesOfHabits");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.ToTable("ProgressesOfHabits", "hbt");
                });

            modelBuilder.Entity("SET.Shared.Models.Statement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statements");
                });

            modelBuilder.Entity("SET.Shared.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR SQ_Users");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("MainSlogan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Mission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varbinary");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLife", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR SQ_UserAreasOfLife");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAreasOfLife", "arlf");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLifeUserHabit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR SQ_UserAreasOfLifeUserHabit");

                    b.Property<long>("AreaOfLifeId")
                        .HasColumnType("bigint");

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AreaOfLifeId");

                    b.HasIndex("HabitId");

                    b.ToTable("UserAreasOfLifeUserHabits", "arlf");
                });

            modelBuilder.Entity("SET.Shared.Models.UserHabit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR SQ_UserHabits");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Complexity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FrequencyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("PercentageAchieved")
                        .HasColumnType("decimal(17, 16)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonToFollow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FrequencyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHabits", "hbt");
                });

            modelBuilder.Entity("UserHabitUserHabit", b =>
                {
                    b.Property<long>("ParentHabitsId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubHabitsId")
                        .HasColumnType("bigint");

                    b.HasKey("ParentHabitsId", "SubHabitsId");

                    b.HasIndex("SubHabitsId");

                    b.ToTable("UserHabitUserHabit", "hbt");
                });

            modelBuilder.Entity("SET.Shared.Models.FileEntity", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.ProgressOfHabit", b =>
                {
                    b.HasOne("SET.Shared.Models.UserHabit", "Habit")
                        .WithMany("Progresses")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLife", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany("AreasOfLife")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLifeUserHabit", b =>
                {
                    b.HasOne("SET.Shared.Models.UserAreaOfLife", "AreaOfLife")
                        .WithMany("Habits")
                        .HasForeignKey("AreaOfLifeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.UserHabit", "Habit")
                        .WithMany("AreasOfLife")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaOfLife");

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("SET.Shared.Models.UserHabit", b =>
                {
                    b.HasOne("SET.Shared.Models.Frequency", "Frequency")
                        .WithMany("Habits")
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany("Habits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Frequency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserHabitUserHabit", b =>
                {
                    b.HasOne("SET.Shared.Models.UserHabit", null)
                        .WithMany()
                        .HasForeignKey("ParentHabitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.UserHabit", null)
                        .WithMany()
                        .HasForeignKey("SubHabitsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SET.Shared.Models.Frequency", b =>
                {
                    b.Navigation("Habits");
                });

            modelBuilder.Entity("SET.Shared.Models.User", b =>
                {
                    b.Navigation("AreasOfLife");

                    b.Navigation("Habits");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLife", b =>
                {
                    b.Navigation("Habits");
                });

            modelBuilder.Entity("SET.Shared.Models.UserHabit", b =>
                {
                    b.Navigation("AreasOfLife");

                    b.Navigation("Progresses");
                });
#pragma warning restore 612, 618
        }
    }
}
