// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SET.DataAccess;

#nullable disable

namespace SET.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240604154003_AddedUserPrinciplesAndPrincipleProgress")]
    partial class AddedUserPrinciplesAndPrincipleProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("sq__client_logs", "app")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__file_entities", "app")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__frequencies", "app")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__principle_progresses", "prc")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__progresses_of_habits", "hbt")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__statements", "app")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__user_areas_of_life", "arlf")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__user_areas_of_life_user_habits", "arlf")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__user_habits", "hbt")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__user_principles", "prc")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__users", "app")
                .StartsAt(100L);

            modelBuilder.Entity("SET.Shared.Models.ClientLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__client_logs')");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DeviceManufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceOs")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LogMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ClientLogs", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.FileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__file_entities')");

                    b.Property<string>("FileExtension")
                        .HasColumnType("text");

                    b.Property<int>("FilePurpose")
                        .HasColumnType("integer");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FileEntities", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.Frequency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__frequencies')");

                    b.Property<int>("IntervalLengthInDays")
                        .HasColumnType("integer");

                    b.Property<int>("Repeats")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(7, 6)");

                    b.HasKey("Id");

                    b.ToTable("Frequencies", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.PrincipleProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('prc.sq__principle_progresses')");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("PrincipleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrincipleId");

                    b.ToTable("PrincipleProgresses", "prc");
                });

            modelBuilder.Entity("SET.Shared.Models.ProgressOfHabit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('hbt.sq__progresses_of_habits')");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.ToTable("ProgressesOfHabits", "hbt");
                });

            modelBuilder.Entity("SET.Shared.Models.Statement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__statements')");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Statements", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__users')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("MainSlogan")
                        .HasColumnType("text");

                    b.Property<string>("Mission")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Users", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLife", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('arlf.sq__user_areas_of_life')");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAreasOfLife", "arlf");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLifeUserHabit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('arlf.sq__user_areas_of_life_user_habits')");

                    b.Property<long>("AreaOfLifeId")
                        .HasColumnType("bigint");

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AreaOfLifeId");

                    b.HasIndex("HabitId");

                    b.ToTable("UserAreasOfLifeUserHabits", "arlf");
                });

            modelBuilder.Entity("SET.Shared.Models.UserHabit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('hbt.sq__user_habits')");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("FrequencyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("PercentageAchieved")
                        .HasColumnType("decimal(17, 16)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<string>("ReasonToFollow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FrequencyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHabits", "hbt");
                });

            modelBuilder.Entity("SET.Shared.Models.UserPrinciple", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('prc.sq__user_principles')");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Exceptions")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonToFollow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserPrinciples", "prc");
                });

            modelBuilder.Entity("UserHabitUserHabit", b =>
                {
                    b.Property<long>("ParentHabitsId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubHabitsId")
                        .HasColumnType("bigint");

                    b.HasKey("ParentHabitsId", "SubHabitsId");

                    b.HasIndex("SubHabitsId");

                    b.ToTable("UserHabitUserHabit", "hbt");
                });

            modelBuilder.Entity("SET.Shared.Models.ClientLog", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany("ClientLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.FileEntity", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.PrincipleProgress", b =>
                {
                    b.HasOne("SET.Shared.Models.UserPrinciple", "Principle")
                        .WithMany("Progresses")
                        .HasForeignKey("PrincipleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Principle");
                });

            modelBuilder.Entity("SET.Shared.Models.ProgressOfHabit", b =>
                {
                    b.HasOne("SET.Shared.Models.UserHabit", "Habit")
                        .WithMany("Progresses")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLife", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany("AreasOfLife")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLifeUserHabit", b =>
                {
                    b.HasOne("SET.Shared.Models.UserAreaOfLife", "AreaOfLife")
                        .WithMany("Habits")
                        .HasForeignKey("AreaOfLifeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.UserHabit", "Habit")
                        .WithMany("AreasOfLife")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaOfLife");

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("SET.Shared.Models.UserHabit", b =>
                {
                    b.HasOne("SET.Shared.Models.Frequency", "Frequency")
                        .WithMany("Habits")
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany("Habits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Frequency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserHabitUserHabit", b =>
                {
                    b.HasOne("SET.Shared.Models.UserHabit", null)
                        .WithMany()
                        .HasForeignKey("ParentHabitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.UserHabit", null)
                        .WithMany()
                        .HasForeignKey("SubHabitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SET.Shared.Models.Frequency", b =>
                {
                    b.Navigation("Habits");
                });

            modelBuilder.Entity("SET.Shared.Models.User", b =>
                {
                    b.Navigation("AreasOfLife");

                    b.Navigation("ClientLogs");

                    b.Navigation("Habits");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLife", b =>
                {
                    b.Navigation("Habits");
                });

            modelBuilder.Entity("SET.Shared.Models.UserHabit", b =>
                {
                    b.Navigation("AreasOfLife");

                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("SET.Shared.Models.UserPrinciple", b =>
                {
                    b.Navigation("Progresses");
                });
#pragma warning restore 612, 618
        }
    }
}
