// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SET.DataAccess;

#nullable disable

namespace SET.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930131126_AddNotesToUserGoals")]
    partial class AddNotesToUserGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("sq__client_logs", "app")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__frequencies", "app")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__progresses_of_habits", "hbt")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__sync_deletions", "app")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__tracking__of__user__notification__requests", "app")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__user_areas_of_life", "arlf")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__user_areas_of_life_user_habits", "arlf")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__user_devices", "app")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__user_goals", "goal")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__user_habit_reminders", "hbt")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__user_habits", "hbt")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__user_reminders", "app")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__users", "app")
                .StartsAt(100L);

            modelBuilder.HasSequence("sq__week_days", "app")
                .StartsAt(100L);

            modelBuilder.Entity("SET.Shared.Models.AiConversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ClientId")
                        .IsUnique();

                    b.ToTable("AiConversations", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.AiMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ConversationId", "ClientId")
                        .IsUnique();

                    b.ToTable("AiMessages", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.ClientLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__client_logs')");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'Europe/Kiev'");

                    b.Property<string>("DeviceManufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceOs")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LogMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ClientLogs", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.Frequency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__frequencies')");

                    b.Property<int>("IntervalLengthInDays")
                        .HasColumnType("integer");

                    b.Property<int>("Repeats")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Frequencies", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.ProgressOfHabit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('hbt.sq__progresses_of_habits')");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.ToTable("ProgressesOfHabits", "hbt");
                });

            modelBuilder.Entity("SET.Shared.Models.SyncDeletion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__sync_deletions')");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeletedAt");

                    b.HasIndex("UserId", "EntityType", "EntityId");

                    b.ToTable("SyncDeletions", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("ConstantNotificationRequestId")
                        .HasColumnType("integer");

                    b.Property<bool>("ConstantReminder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RemindersJson")
                        .HasColumnType("text");

                    b.Property<string>("RepeatJson")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("Tasks", "tsk");
                });

            modelBuilder.Entity("SET.Shared.Models.TaskSubtask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskId", "ClientId")
                        .IsUnique();

                    b.ToTable("TaskSubtasks", "tsk");
                });

            modelBuilder.Entity("SET.Shared.Models.TrackingOfUserNotificationRequests", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__tracking__of__user__notification__requests')");

                    b.Property<int>("MaxNotificationRequestId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TrackingOfUserNotificationRequests", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__users')");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("HasSeenRoadGuide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MainSlogan")
                        .HasColumnType("text");

                    b.Property<string>("Mission")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLife", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('arlf.sq__user_areas_of_life')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAreasOfLife", "arlf");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLifeUserHabit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('arlf.sq__user_areas_of_life_user_habits')");

                    b.Property<long>("AreaOfLifeId")
                        .HasColumnType("bigint");

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AreaOfLifeId");

                    b.HasIndex("HabitId");

                    b.ToTable("UserAreasOfLifeUserHabits", "arlf");
                });

            modelBuilder.Entity("SET.Shared.Models.UserDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__user_devices')");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserDevices", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.UserGoal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('goal.sq__user_goals')");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserGoals", "goal");
                });

            modelBuilder.Entity("SET.Shared.Models.UserHabit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('hbt.sq__user_habits')");

                    b.Property<bool>("AllDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ArchivingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer");

                    b.Property<bool>("ConstantReminder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<long>("FrequencyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GoalId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ProgressMarkVariaty")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<string>("ReasonToFollow")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<double?>("TargetPerOneTime")
                        .HasColumnType("double precision");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FrequencyId");

                    b.HasIndex("GoalId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHabits", "hbt");
                });

            modelBuilder.Entity("SET.Shared.Models.UserHabitReminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('hbt.sq__user_habit_reminders')");

                    b.Property<bool>("AllDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("ConstantNotificationRequestId")
                        .HasColumnType("integer");

                    b.Property<bool>("ConstantReminder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("OffsetsJson")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserHabitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserHabitId");

                    b.ToTable("UserHabitReminders", "hbt");
                });

            modelBuilder.Entity("SET.Shared.Models.UserReminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__user_reminders')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserNotificationRequestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserReminders", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.WeekDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('app.sq__week_days')");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("UserHabitReminderId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserNotificationRequestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserHabitReminderId");

                    b.ToTable("WeekDays", "app");
                });

            modelBuilder.Entity("SET.Shared.Models.AiConversation", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.AiMessage", b =>
                {
                    b.HasOne("SET.Shared.Models.AiConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("SET.Shared.Models.ClientLog", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany("ClientLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.ProgressOfHabit", b =>
                {
                    b.HasOne("SET.Shared.Models.UserHabit", "Habit")
                        .WithMany("Progresses")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("SET.Shared.Models.SyncDeletion", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.Task", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.TaskSubtask", b =>
                {
                    b.HasOne("SET.Shared.Models.Task", "Task")
                        .WithMany("Subtasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SET.Shared.Models.TrackingOfUserNotificationRequests", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany("TrackingOfUserNotificationRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLife", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany("AreasOfLife")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLifeUserHabit", b =>
                {
                    b.HasOne("SET.Shared.Models.UserAreaOfLife", "AreaOfLife")
                        .WithMany("Habits")
                        .HasForeignKey("AreaOfLifeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.UserHabit", "Habit")
                        .WithMany("AreasOfLife")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaOfLife");

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("SET.Shared.Models.UserDevice", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.UserGoal", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.UserHabit", b =>
                {
                    b.HasOne("SET.Shared.Models.Frequency", "Frequency")
                        .WithMany("Habits")
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SET.Shared.Models.UserGoal", "Goal")
                        .WithMany("UserHabits")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithMany("Habits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Frequency");

                    b.Navigation("Goal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.UserHabitReminder", b =>
                {
                    b.HasOne("SET.Shared.Models.UserHabit", "UserHabit")
                        .WithMany("Reminders")
                        .HasForeignKey("UserHabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserHabit");
                });

            modelBuilder.Entity("SET.Shared.Models.UserReminder", b =>
                {
                    b.HasOne("SET.Shared.Models.User", "User")
                        .WithOne("HabitsReportReminder")
                        .HasForeignKey("SET.Shared.Models.UserReminder", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SET.Shared.Models.WeekDay", b =>
                {
                    b.HasOne("SET.Shared.Models.UserHabitReminder", "UserHabitReminder")
                        .WithMany("DaysOfWeek")
                        .HasForeignKey("UserHabitReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserHabitReminder");
                });

            modelBuilder.Entity("SET.Shared.Models.AiConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SET.Shared.Models.Frequency", b =>
                {
                    b.Navigation("Habits");
                });

            modelBuilder.Entity("SET.Shared.Models.Task", b =>
                {
                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("SET.Shared.Models.User", b =>
                {
                    b.Navigation("AreasOfLife");

                    b.Navigation("ClientLogs");

                    b.Navigation("Goals");

                    b.Navigation("Habits");

                    b.Navigation("HabitsReportReminder");

                    b.Navigation("TrackingOfUserNotificationRequests");
                });

            modelBuilder.Entity("SET.Shared.Models.UserAreaOfLife", b =>
                {
                    b.Navigation("Habits");
                });

            modelBuilder.Entity("SET.Shared.Models.UserGoal", b =>
                {
                    b.Navigation("UserHabits");
                });

            modelBuilder.Entity("SET.Shared.Models.UserHabit", b =>
                {
                    b.Navigation("AreasOfLife");

                    b.Navigation("Progresses");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("SET.Shared.Models.UserHabitReminder", b =>
                {
                    b.Navigation("DaysOfWeek");
                });
#pragma warning restore 612, 618
        }
    }
}
