// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SET.DataAccess;

#nullable disable

namespace SET.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905163000_ExpandTaskNotesToText")]
    partial class ExpandTaskNotesToText
    {
    }
}
